name: Publish documentation
on:
  push:
    branches:
      - main
    # paths:
    #   - documentation
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install .[documentation]
      - run: mkdocs gh-deploy --theme material --force --verbose