name: Publish documentation
on:
  push:
    branches:
      - 'main'
    paths:
      - 'documentation/**'  # Any changes in the documentation folder
      - 'mkdocs.yml'         # Any changes to the mkdocs.yml file
      
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install .[documentation]
      - run: mkdocs gh-deploy --force --verbose